#index:
#    path: /
#    controller: App\Controller\DefaultController::index
login:
  path: /login
  controller: App\SecurityController::login

register:
  path: /register
  controller: App\RegistrationController::register

fichefrais:
  path: /fichefrais
  controller: App\FicheFraisController::ficheFrais